version: "3.7"
services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - 8090:8080
    volumes:
      - ./jenkins:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - deployment-network
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - sonarqube-demo
    networks:
      - deployment-network
volumes:
  jenkins:
  sonarqube-demo:
networks:
  deployment-network: